/* tslint:disable */
/* eslint-disable */
/**
 * Service
 * Service description...  Generated by genpjrpc: v0.5.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModelsResponse
 */
export interface ModelsResponse {
    /**
     * 
     * @type {string}
     * @memberof ModelsResponse
     */
    greeting: string;
}

/**
 * Check if a given object implements the ModelsResponse interface.
 */
export function instanceOfModelsResponse(value: object): value is ModelsResponse {
    if (!('greeting' in value) || value['greeting'] === undefined) return false;
    return true;
}

export function ModelsResponseFromJSON(json: any): ModelsResponse {
    return ModelsResponseFromJSONTyped(json, false);
}

export function ModelsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'greeting': json['greeting'],
    };
}

export function ModelsResponseToJSON(json: any): ModelsResponse {
    return ModelsResponseToJSONTyped(json, false);
}

export function ModelsResponseToJSONTyped(value?: ModelsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'greeting': value['greeting'],
    };
}

