/* tslint:disable */
/* eslint-disable */
/**
 * Service
 * Service description...  Generated by genpjrpc: v0.5.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModelsGetGreetingResponse
 */
export interface ModelsGetGreetingResponse {
    /**
     * 
     * @type {string}
     * @memberof ModelsGetGreetingResponse
     */
    greeting: string;
}

/**
 * Check if a given object implements the ModelsGetGreetingResponse interface.
 */
export function instanceOfModelsGetGreetingResponse(value: object): value is ModelsGetGreetingResponse {
    if (!('greeting' in value) || value['greeting'] === undefined) return false;
    return true;
}

export function ModelsGetGreetingResponseFromJSON(json: any): ModelsGetGreetingResponse {
    return ModelsGetGreetingResponseFromJSONTyped(json, false);
}

export function ModelsGetGreetingResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelsGetGreetingResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'greeting': json['greeting'],
    };
}

export function ModelsGetGreetingResponseToJSON(json: any): ModelsGetGreetingResponse {
    return ModelsGetGreetingResponseToJSONTyped(json, false);
}

export function ModelsGetGreetingResponseToJSONTyped(value?: ModelsGetGreetingResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'greeting': value['greeting'],
    };
}

