/* tslint:disable */
/* eslint-disable */
/**
 * Service
 * Service description...  Generated by genpjrpc: v0.5.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModelsRequest
 */
export interface ModelsRequest {
    /**
     * 
     * @type {string}
     * @memberof ModelsRequest
     */
    thing: string;
}

/**
 * Check if a given object implements the ModelsRequest interface.
 */
export function instanceOfModelsRequest(value: object): value is ModelsRequest {
    if (!('thing' in value) || value['thing'] === undefined) return false;
    return true;
}

export function ModelsRequestFromJSON(json: any): ModelsRequest {
    return ModelsRequestFromJSONTyped(json, false);
}

export function ModelsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'thing': json['thing'],
    };
}

export function ModelsRequestToJSON(json: any): ModelsRequest {
    return ModelsRequestToJSONTyped(json, false);
}

export function ModelsRequestToJSONTyped(value?: ModelsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'thing': value['thing'],
    };
}

