/* tslint:disable */
/* eslint-disable */
/**
 * Service
 * Service description...  Generated by genpjrpc: v0.5.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModelsGetGreetingRequest
 */
export interface ModelsGetGreetingRequest {
    /**
     * 
     * @type {string}
     * @memberof ModelsGetGreetingRequest
     */
    thing: string;
}

/**
 * Check if a given object implements the ModelsGetGreetingRequest interface.
 */
export function instanceOfModelsGetGreetingRequest(value: object): value is ModelsGetGreetingRequest {
    if (!('thing' in value) || value['thing'] === undefined) return false;
    return true;
}

export function ModelsGetGreetingRequestFromJSON(json: any): ModelsGetGreetingRequest {
    return ModelsGetGreetingRequestFromJSONTyped(json, false);
}

export function ModelsGetGreetingRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelsGetGreetingRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'thing': json['thing'],
    };
}

export function ModelsGetGreetingRequestToJSON(json: any): ModelsGetGreetingRequest {
    return ModelsGetGreetingRequestToJSONTyped(json, false);
}

export function ModelsGetGreetingRequestToJSONTyped(value?: ModelsGetGreetingRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'thing': value['thing'],
    };
}

