/* tslint:disable */
/* eslint-disable */
/**
 * Service
 * Service description...  Generated by genpjrpc: v0.5.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ModelsRequest } from './ModelsRequest';
import {
    ModelsRequestFromJSON,
    ModelsRequestFromJSONTyped,
    ModelsRequestToJSON,
    ModelsRequestToJSONTyped,
} from './ModelsRequest';

/**
 * 
 * @export
 * @interface RequestBodyOfTheMethodMethod
 */
export interface RequestBodyOfTheMethodMethod {
    /**
     * A String specifying the version of the JSON-RPC protocol. MUST be exactly "2.0".
     * @type {string}
     * @memberof RequestBodyOfTheMethodMethod
     */
    jsonrpc?: RequestBodyOfTheMethodMethodJsonrpcEnum;
    /**
     * An identifier established by the Client.
     * @type {string}
     * @memberof RequestBodyOfTheMethodMethod
     */
    id?: string;
    /**
     * A String containing the name of the method to be invoked.
     * @type {string}
     * @memberof RequestBodyOfTheMethodMethod
     */
    method?: RequestBodyOfTheMethodMethodMethodEnum;
    /**
     * 
     * @type {ModelsRequest}
     * @memberof RequestBodyOfTheMethodMethod
     */
    params?: ModelsRequest;
}


/**
 * @export
 */
export const RequestBodyOfTheMethodMethodJsonrpcEnum = {
    _20: '2.0'
} as const;
export type RequestBodyOfTheMethodMethodJsonrpcEnum = typeof RequestBodyOfTheMethodMethodJsonrpcEnum[keyof typeof RequestBodyOfTheMethodMethodJsonrpcEnum];

/**
 * @export
 */
export const RequestBodyOfTheMethodMethodMethodEnum = {
    Method: 'method'
} as const;
export type RequestBodyOfTheMethodMethodMethodEnum = typeof RequestBodyOfTheMethodMethodMethodEnum[keyof typeof RequestBodyOfTheMethodMethodMethodEnum];


/**
 * Check if a given object implements the RequestBodyOfTheMethodMethod interface.
 */
export function instanceOfRequestBodyOfTheMethodMethod(value: object): value is RequestBodyOfTheMethodMethod {
    return true;
}

export function RequestBodyOfTheMethodMethodFromJSON(json: any): RequestBodyOfTheMethodMethod {
    return RequestBodyOfTheMethodMethodFromJSONTyped(json, false);
}

export function RequestBodyOfTheMethodMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestBodyOfTheMethodMethod {
    if (json == null) {
        return json;
    }
    return {
        
        'jsonrpc': json['jsonrpc'] == null ? undefined : json['jsonrpc'],
        'id': json['id'] == null ? undefined : json['id'],
        'method': json['method'] == null ? undefined : json['method'],
        'params': json['params'] == null ? undefined : ModelsRequestFromJSON(json['params']),
    };
}

export function RequestBodyOfTheMethodMethodToJSON(json: any): RequestBodyOfTheMethodMethod {
    return RequestBodyOfTheMethodMethodToJSONTyped(json, false);
}

export function RequestBodyOfTheMethodMethodToJSONTyped(value?: RequestBodyOfTheMethodMethod | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'jsonrpc': value['jsonrpc'],
        'id': value['id'],
        'method': value['method'],
        'params': ModelsRequestToJSON(value['params']),
    };
}

