/* tslint:disable */
/* eslint-disable */
/**
 * Service
 * Service description...  Generated by genpjrpc: v0.5.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ModelsGetGreetingRequest } from './ModelsGetGreetingRequest';
import {
    ModelsGetGreetingRequestFromJSON,
    ModelsGetGreetingRequestFromJSONTyped,
    ModelsGetGreetingRequestToJSON,
    ModelsGetGreetingRequestToJSONTyped,
} from './ModelsGetGreetingRequest';

/**
 * 
 * @export
 * @interface RequestBodyOfTheGetGreetingMethod
 */
export interface RequestBodyOfTheGetGreetingMethod {
    /**
     * A String specifying the version of the JSON-RPC protocol. MUST be exactly "2.0".
     * @type {string}
     * @memberof RequestBodyOfTheGetGreetingMethod
     */
    jsonrpc?: RequestBodyOfTheGetGreetingMethodJsonrpcEnum;
    /**
     * An identifier established by the Client.
     * @type {string}
     * @memberof RequestBodyOfTheGetGreetingMethod
     */
    id?: string;
    /**
     * A String containing the name of the method to be invoked.
     * @type {string}
     * @memberof RequestBodyOfTheGetGreetingMethod
     */
    method?: RequestBodyOfTheGetGreetingMethodMethodEnum;
    /**
     * 
     * @type {ModelsGetGreetingRequest}
     * @memberof RequestBodyOfTheGetGreetingMethod
     */
    params?: ModelsGetGreetingRequest;
}


/**
 * @export
 */
export const RequestBodyOfTheGetGreetingMethodJsonrpcEnum = {
    _20: '2.0'
} as const;
export type RequestBodyOfTheGetGreetingMethodJsonrpcEnum = typeof RequestBodyOfTheGetGreetingMethodJsonrpcEnum[keyof typeof RequestBodyOfTheGetGreetingMethodJsonrpcEnum];

/**
 * @export
 */
export const RequestBodyOfTheGetGreetingMethodMethodEnum = {
    GetGreeting: 'get_greeting'
} as const;
export type RequestBodyOfTheGetGreetingMethodMethodEnum = typeof RequestBodyOfTheGetGreetingMethodMethodEnum[keyof typeof RequestBodyOfTheGetGreetingMethodMethodEnum];


/**
 * Check if a given object implements the RequestBodyOfTheGetGreetingMethod interface.
 */
export function instanceOfRequestBodyOfTheGetGreetingMethod(value: object): value is RequestBodyOfTheGetGreetingMethod {
    return true;
}

export function RequestBodyOfTheGetGreetingMethodFromJSON(json: any): RequestBodyOfTheGetGreetingMethod {
    return RequestBodyOfTheGetGreetingMethodFromJSONTyped(json, false);
}

export function RequestBodyOfTheGetGreetingMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestBodyOfTheGetGreetingMethod {
    if (json == null) {
        return json;
    }
    return {
        
        'jsonrpc': json['jsonrpc'] == null ? undefined : json['jsonrpc'],
        'id': json['id'] == null ? undefined : json['id'],
        'method': json['method'] == null ? undefined : json['method'],
        'params': json['params'] == null ? undefined : ModelsGetGreetingRequestFromJSON(json['params']),
    };
}

export function RequestBodyOfTheGetGreetingMethodToJSON(json: any): RequestBodyOfTheGetGreetingMethod {
    return RequestBodyOfTheGetGreetingMethodToJSONTyped(json, false);
}

export function RequestBodyOfTheGetGreetingMethodToJSONTyped(value?: RequestBodyOfTheGetGreetingMethod | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'jsonrpc': value['jsonrpc'],
        'id': value['id'],
        'method': value['method'],
        'params': ModelsGetGreetingRequestToJSON(value['params']),
    };
}

