/* tslint:disable */
/* eslint-disable */
/**
 * Service
 * Service description...  Generated by genpjrpc: v0.5.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ModelsResponse } from './ModelsResponse';
import {
    ModelsResponseFromJSON,
    ModelsResponseFromJSONTyped,
    ModelsResponseToJSON,
    ModelsResponseToJSONTyped,
} from './ModelsResponse';
import type { RpcError } from './RpcError';
import {
    RpcErrorFromJSON,
    RpcErrorFromJSONTyped,
    RpcErrorToJSON,
    RpcErrorToJSONTyped,
} from './RpcError';

/**
 * 
 * @export
 * @interface ResponseBodyOfTheMethodMethod
 */
export interface ResponseBodyOfTheMethodMethod {
    /**
     * A String specifying the version of the JSON-RPC protocol. MUST be exactly "2.0".
     * @type {string}
     * @memberof ResponseBodyOfTheMethodMethod
     */
    jsonrpc?: ResponseBodyOfTheMethodMethodJsonrpcEnum;
    /**
     * It MUST be the same as the value of the id member in the Request.
     * @type {string}
     * @memberof ResponseBodyOfTheMethodMethod
     */
    id?: string;
    /**
     * 
     * @type {RpcError}
     * @memberof ResponseBodyOfTheMethodMethod
     */
    error?: RpcError;
    /**
     * 
     * @type {ModelsResponse}
     * @memberof ResponseBodyOfTheMethodMethod
     */
    result?: ModelsResponse;
}


/**
 * @export
 */
export const ResponseBodyOfTheMethodMethodJsonrpcEnum = {
    _20: '2.0'
} as const;
export type ResponseBodyOfTheMethodMethodJsonrpcEnum = typeof ResponseBodyOfTheMethodMethodJsonrpcEnum[keyof typeof ResponseBodyOfTheMethodMethodJsonrpcEnum];


/**
 * Check if a given object implements the ResponseBodyOfTheMethodMethod interface.
 */
export function instanceOfResponseBodyOfTheMethodMethod(value: object): value is ResponseBodyOfTheMethodMethod {
    return true;
}

export function ResponseBodyOfTheMethodMethodFromJSON(json: any): ResponseBodyOfTheMethodMethod {
    return ResponseBodyOfTheMethodMethodFromJSONTyped(json, false);
}

export function ResponseBodyOfTheMethodMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseBodyOfTheMethodMethod {
    if (json == null) {
        return json;
    }
    return {
        
        'jsonrpc': json['jsonrpc'] == null ? undefined : json['jsonrpc'],
        'id': json['id'] == null ? undefined : json['id'],
        'error': json['error'] == null ? undefined : RpcErrorFromJSON(json['error']),
        'result': json['result'] == null ? undefined : ModelsResponseFromJSON(json['result']),
    };
}

export function ResponseBodyOfTheMethodMethodToJSON(json: any): ResponseBodyOfTheMethodMethod {
    return ResponseBodyOfTheMethodMethodToJSONTyped(json, false);
}

export function ResponseBodyOfTheMethodMethodToJSONTyped(value?: ResponseBodyOfTheMethodMethod | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'jsonrpc': value['jsonrpc'],
        'id': value['id'],
        'error': RpcErrorToJSON(value['error']),
        'result': ModelsResponseToJSON(value['result']),
    };
}

