/* tslint:disable */
/* eslint-disable */
/**
 * Service
 * Service description...  Generated by genpjrpc: v0.5.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RpcError } from './RpcError';
import {
    RpcErrorFromJSON,
    RpcErrorFromJSONTyped,
    RpcErrorToJSON,
    RpcErrorToJSONTyped,
} from './RpcError';
import type { ModelsGetGreetingResponse } from './ModelsGetGreetingResponse';
import {
    ModelsGetGreetingResponseFromJSON,
    ModelsGetGreetingResponseFromJSONTyped,
    ModelsGetGreetingResponseToJSON,
    ModelsGetGreetingResponseToJSONTyped,
} from './ModelsGetGreetingResponse';

/**
 * 
 * @export
 * @interface ResponseBodyOfTheGetGreetingMethod
 */
export interface ResponseBodyOfTheGetGreetingMethod {
    /**
     * A String specifying the version of the JSON-RPC protocol. MUST be exactly "2.0".
     * @type {string}
     * @memberof ResponseBodyOfTheGetGreetingMethod
     */
    jsonrpc?: ResponseBodyOfTheGetGreetingMethodJsonrpcEnum;
    /**
     * It MUST be the same as the value of the id member in the Request.
     * @type {string}
     * @memberof ResponseBodyOfTheGetGreetingMethod
     */
    id?: string;
    /**
     * 
     * @type {RpcError}
     * @memberof ResponseBodyOfTheGetGreetingMethod
     */
    error?: RpcError;
    /**
     * 
     * @type {ModelsGetGreetingResponse}
     * @memberof ResponseBodyOfTheGetGreetingMethod
     */
    result?: ModelsGetGreetingResponse;
}


/**
 * @export
 */
export const ResponseBodyOfTheGetGreetingMethodJsonrpcEnum = {
    _20: '2.0'
} as const;
export type ResponseBodyOfTheGetGreetingMethodJsonrpcEnum = typeof ResponseBodyOfTheGetGreetingMethodJsonrpcEnum[keyof typeof ResponseBodyOfTheGetGreetingMethodJsonrpcEnum];


/**
 * Check if a given object implements the ResponseBodyOfTheGetGreetingMethod interface.
 */
export function instanceOfResponseBodyOfTheGetGreetingMethod(value: object): value is ResponseBodyOfTheGetGreetingMethod {
    return true;
}

export function ResponseBodyOfTheGetGreetingMethodFromJSON(json: any): ResponseBodyOfTheGetGreetingMethod {
    return ResponseBodyOfTheGetGreetingMethodFromJSONTyped(json, false);
}

export function ResponseBodyOfTheGetGreetingMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseBodyOfTheGetGreetingMethod {
    if (json == null) {
        return json;
    }
    return {
        
        'jsonrpc': json['jsonrpc'] == null ? undefined : json['jsonrpc'],
        'id': json['id'] == null ? undefined : json['id'],
        'error': json['error'] == null ? undefined : RpcErrorFromJSON(json['error']),
        'result': json['result'] == null ? undefined : ModelsGetGreetingResponseFromJSON(json['result']),
    };
}

export function ResponseBodyOfTheGetGreetingMethodToJSON(json: any): ResponseBodyOfTheGetGreetingMethod {
    return ResponseBodyOfTheGetGreetingMethodToJSONTyped(json, false);
}

export function ResponseBodyOfTheGetGreetingMethodToJSONTyped(value?: ResponseBodyOfTheGetGreetingMethod | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'jsonrpc': value['jsonrpc'],
        'id': value['id'],
        'error': RpcErrorToJSON(value['error']),
        'result': ModelsGetGreetingResponseToJSON(value['result']),
    };
}

