/* tslint:disable */
/* eslint-disable */
/**
 * Service
 * Service description...  Generated by genpjrpc: v0.5.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * REQUIRED on error. This member MUST NOT exist if there was no error triggered during invocation.
 * @export
 * @interface RpcError
 */
export interface RpcError {
    /**
     * A Number that indicates the error type that occurred.
     * @type {number}
     * @memberof RpcError
     */
    code?: number;
    /**
     * A String providing a short description of the error.
     * @type {string}
     * @memberof RpcError
     */
    message?: string;
    /**
     * A Primitive or Structured value that contains additional information about the error.
     * @type {object}
     * @memberof RpcError
     */
    data?: object;
}

/**
 * Check if a given object implements the RpcError interface.
 */
export function instanceOfRpcError(value: object): value is RpcError {
    return true;
}

export function RpcErrorFromJSON(json: any): RpcError {
    return RpcErrorFromJSONTyped(json, false);
}

export function RpcErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): RpcError {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : json['data'],
    };
}

export function RpcErrorToJSON(json: any): RpcError {
    return RpcErrorToJSONTyped(json, false);
}

export function RpcErrorToJSONTyped(value?: RpcError | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'data': value['data'],
    };
}

