// Code generated by genpjrpc. DO NOT EDIT.
//  genpjrpc version: v0.5.0
//mockgen

package rpcclient

import (
	"context"
	"fmt"

	"github.com/google/uuid"
	"gitlab.com/pjrpc/pjrpc/v2/client"

	"hello-world/internal/handlers/models"
)

// List of the client JSON-RPC methods.
const (
	JSONRPCMethodGetGreeting_Client = "get_greeting"
)

// ServiceClient is an API client for Service service.
type ServiceClient interface {
	GetGreeting(ctx context.Context, in *models.GetGreetingRequest, mods ...client.Mod) (*models.GetGreetingResponse, error)
}

type implServiceClient struct {
	cl client.Invoker
}

// NewServiceClient returns new client implementation of the Service service.
func NewServiceClient(cl client.Invoker) ServiceClient {
	return &implServiceClient{cl: cl}
}

func (c *implServiceClient) GetGreeting(ctx context.Context, in *models.GetGreetingRequest, mods ...client.Mod) (result *models.GetGreetingResponse, err error) {
	gen, err := uuid.NewUUID()
	if err != nil {
		return result, fmt.Errorf("failed to create uuid generator: %w", err)
	}

	result = new(models.GetGreetingResponse)

	err = c.cl.Invoke(ctx, gen.String(), JSONRPCMethodGetGreeting_Client, in, result, mods...)
	if err != nil {
		return result, fmt.Errorf("failed to Invoke method %q: %w", JSONRPCMethodGetGreeting_Client, err)
	}

	return result, nil
}
