// Code generated by MockGen. DO NOT EDIT.
// Source: pjrpc_client_service.go
//
// Generated by this command:
//
//	mockgen -source=pjrpc_client_service.go -destination=pjrpc_client_service.go.mock.go -package=rpcclient -build_flags="-tags=mockgen"
//

// Package rpcclient is a generated GoMock package.
package rpcclient

import (
	context "context"
	models "hello-world/internal/handlers/models"
	reflect "reflect"

	client "gitlab.com/pjrpc/pjrpc/v2/client"
	gomock "go.uber.org/mock/gomock"
)

// MockServiceClient is a mock of ServiceClient interface.
type MockServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockServiceClientMockRecorder
	isgomock struct{}
}

// MockServiceClientMockRecorder is the mock recorder for MockServiceClient.
type MockServiceClientMockRecorder struct {
	mock *MockServiceClient
}

// NewMockServiceClient creates a new mock instance.
func NewMockServiceClient(ctrl *gomock.Controller) *MockServiceClient {
	mock := &MockServiceClient{ctrl: ctrl}
	mock.recorder = &MockServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceClient) EXPECT() *MockServiceClientMockRecorder {
	return m.recorder
}

// GetGreeting mocks base method.
func (m *MockServiceClient) GetGreeting(ctx context.Context, in *models.GetGreetingRequest, mods ...client.Mod) (*models.GetGreetingResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range mods {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetGreeting", varargs...)
	ret0, _ := ret[0].(*models.GetGreetingResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGreeting indicates an expected call of GetGreeting.
func (mr *MockServiceClientMockRecorder) GetGreeting(ctx, in any, mods ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, mods...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGreeting", reflect.TypeOf((*MockServiceClient)(nil).GetGreeting), varargs...)
}
