// Code generated by genpjrpc. DO NOT EDIT.
//  genpjrpc version: v0.5.0
//mockgen

package rpcserver

import (
	"context"
	"encoding/json"
	"fmt"

	pjrpc "gitlab.com/pjrpc/pjrpc/v2"
	"gitlab.com/pjrpc/pjrpc/v2/pjson"

	"hello-world/internal/handlers/models"
)

// List of the server JSON-RPC methods.
const (
	JSONRPCMethodGetGreeting = "get_greeting"
)

// ServiceServer is an API server for Service service.
type ServiceServer interface {
	GetGreeting(ctx context.Context, in *models.GetGreetingRequest) (*models.GetGreetingResponse, error)
}

type regService struct {
	svc ServiceServer
}

// RegisterServiceServer registers rpc handlers with middlewares in the server router.
func RegisterServiceServer(srv pjrpc.Registrator, svc ServiceServer, middlewares ...pjrpc.Middleware) {
	r := &regService{svc: svc}

	srv.RegisterMethod(JSONRPCMethodGetGreeting, r.regGetGreeting)

	srv.With(middlewares...)
}

func (r *regService) regGetGreeting(ctx context.Context, params json.RawMessage) (any, error) {
	in := new(models.GetGreetingRequest)
	if len(params) != 0 {
		if err := pjson.Unmarshal(params, in); err != nil {
			return nil, pjrpc.JRPCErrParseError("failed to parse params")
		}
	}

	res, err := r.svc.GetGreeting(ctx, in)
	if err != nil {
		return nil, fmt.Errorf("failed GetGreeting: %w", err)
	}

	return res, nil
}
