// Code generated by MockGen. DO NOT EDIT.
// Source: pjrpc_server_service.go
//
// Generated by this command:
//
//	mockgen -source=pjrpc_server_service.go -destination=pjrpc_server_service.go.mock.go -package=rpcserver -build_flags="-tags=mockgen"
//

// Package rpcserver is a generated GoMock package.
package rpcserver

import (
	context "context"
	models "hello-world/internal/handlers/models"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockServiceServer is a mock of ServiceServer interface.
type MockServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockServiceServerMockRecorder
	isgomock struct{}
}

// MockServiceServerMockRecorder is the mock recorder for MockServiceServer.
type MockServiceServerMockRecorder struct {
	mock *MockServiceServer
}

// NewMockServiceServer creates a new mock instance.
func NewMockServiceServer(ctrl *gomock.Controller) *MockServiceServer {
	mock := &MockServiceServer{ctrl: ctrl}
	mock.recorder = &MockServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceServer) EXPECT() *MockServiceServerMockRecorder {
	return m.recorder
}

// GetGreeting mocks base method.
func (m *MockServiceServer) GetGreeting(ctx context.Context, in *models.GetGreetingRequest) (*models.GetGreetingResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGreeting", ctx, in)
	ret0, _ := ret[0].(*models.GetGreetingResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGreeting indicates an expected call of GetGreeting.
func (mr *MockServiceServerMockRecorder) GetGreeting(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGreeting", reflect.TypeOf((*MockServiceServer)(nil).GetGreeting), ctx, in)
}
