/* tslint:disable */
/* eslint-disable */
/**
 * Service
 * Service description...  Generated by genpjrpc: v0.5.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  RequestBodyOfTheGetGreetingMethod,
  ResponseBodyOfTheGetGreetingMethod,
} from '../models/index';
import {
    RequestBodyOfTheGetGreetingMethodFromJSON,
    RequestBodyOfTheGetGreetingMethodToJSON,
    ResponseBodyOfTheGetGreetingMethodFromJSON,
    ResponseBodyOfTheGetGreetingMethodToJSON,
} from '../models/index';

export interface GetGreetingRequest {
    requestBodyOfTheGetGreetingMethod: RequestBodyOfTheGetGreetingMethod;
}

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     */
    async getGreetingRaw(requestParameters: GetGreetingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseBodyOfTheGetGreetingMethod>> {
        if (requestParameters['requestBodyOfTheGetGreetingMethod'] == null) {
            throw new runtime.RequiredError(
                'requestBodyOfTheGetGreetingMethod',
                'Required parameter "requestBodyOfTheGetGreetingMethod" was null or undefined when calling getGreeting().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/#get_greeting`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RequestBodyOfTheGetGreetingMethodToJSON(requestParameters['requestBodyOfTheGetGreetingMethod']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseBodyOfTheGetGreetingMethodFromJSON(jsonValue));
    }

    /**
     */
    async getGreeting(requestParameters: GetGreetingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseBodyOfTheGetGreetingMethod> {
        const response = await this.getGreetingRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
